[project]
name = "django-iran-ip"
version = "0.1.0"
description = "A professional Django package for IP detection with Iran network support"
authors = [
    {name = "shayan taki",email = "takishayan@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django (>=4.2,<6.0)",
    "httpx (>=0.28.1,<0.29.0)"
]

[tool.poetry]
packages = [{include = "django_iran_ip", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]